version: '3.8'
services:
#  lumidora-tg-webui:
#    image: lumidora-tg-webui
#    ports:
#      - "7860:7860"
#      - "5000:5000"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
  lumidora-sd-webui:
    image: domoskanonos/lumidora-sd-webui  # Replace with the actual image name
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "7861:7860"
    volumes:
      - lumidora-sd-webui-outputs:/app/stable-diffusion-webui/outputs
      - lumidora-sd-webui-results:/app/stable-diffusion-webui/results
      #- lumidora-sd-webui-extensions:/app/stable-diffusion-webui/extensions/
  lumidora-tts:
    image: lumidora-tts
    ports:
      - "7862:8080"
    volumes:
      - lumidora-tts-models:/go/src/app/models
  lumidora-logging:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9999:8080
volumes:
  lumidora-tts-models:
  lumidora-sd-webui-outputs:
  lumidora-sd-webui-results:
  lumidora-sd-webui-extensions:
